### ISSUE TITLE
No extrude IntersectFeatureOperation in Reconstruction Dataset

### ISSUE THREAD

**Issue by adrelino** [AutodeskAILab/Fusion360GalleryDataset#66] opened 2020-12-09 13:41 UTC
Is there really no extrude `IntersectFeatureOperation` in the whole dataset according to the very bottom of the stats page
(https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/docs/reconstruction_stats.md)?

If so, what might be the reasons for that? Do users rarely extrude 2 shapes to later intersect them to get a smaller shape?

Isn't that a problem for an agent solving the gym environment, bootstrapped with imitiation learning from the reconstruction dataset, since the `IntersectFeatureOperation` action will get initialized with 0 probability and never be explored?

**Comment by karldd** [comment] 2020-12-09 16:32
Good spotting. This looks like some kind of matplotlib pixel rounding error.
Here are the numbers representing the total count of each `FeatureOperation` in the dataset:
```
'NewBodyFeatureOperation': 10304
'JoinFeatureOperation': 4711
'CutFeatureOperation': 4299
'IntersectFeatureOperation': 19
```
As you can see the numbers of `IntersectFeatureOperation` are very low, so it does not appear to be commonly used by designers/engineers using Fusion 360. My guess is that the other operations tend to be more intuitive to work with in most scenarios.

Oddly the low-res inline plot from a Jupyter Notebook seems to show a small blip for `IntersectFeatureOperation`.

![image](https://user-images.githubusercontent.com/619336/101656698-da78fe80-39f7-11eb-8d7c-5dd1dca45e56.png)

**Comment by karldd** [comment] 2020-12-14 22:46
@adrelino I'm going to close this for now. Feel free to reopen if you have other questions.

**Closed by karldd** 2020-12-14 22:46 UTC
Labels: documentation
